version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jbvlpnc2zz76"
s3_prefix = "hello-world-test"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
